MODEL:
  METHOD: "refine"
  META_ARCHITECTURE: "PlaneRCNNRefine"
  WEIGHT: "models/e2e_mask_rcnn_R_50_FPN_1x.pth"
  ACTIVATE_BN_TRAIN: False
  REFINE:
    WITH_WARPING_LOSS: False
    WITH_MASK_REFINE_LOSS: False
    WITH_PEEKABOO_LOSS: False
    GENERATE_PSEUDO_GT: False
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    SCORE_THRESH: 0.05
    NMS_PER_CLS: False
    APPLY_MASK_NMS: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 12
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
DATASETS:
  TRAIN: ("scannet_warping_train", )
  TEST: ("scannet_warping_val", )
DATALOADER:
  SIZE_DIVISIBILITY: 32
  ASPECT_RATIO_GROUPING: False
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 4
  CHECKPOINT_PERIOD: 2500
  TRAIN_BY_EPOCH: True
  TUNE_EPOCHS: (3, 4)
  MAX_EPOCHS: 5
  TEST_PERIOD: 2500
LOG:
  LOG_INTERVAL: 50
INPUT:
  HORIZONTAL_FLIP_PROB_TRAIN: 0.0
  MIN_SIZE_TRAIN: (480,)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 480
  MAX_SIZE_TEST: 1000
OUTPUT_DIR: "debug_outputs"
